source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"

gem "neighbor"
gem "ruby-openai"
gem "redis", ">= 4.0.1"
# Sidekiq 7.3.x is incompatible with connection_pool 3.x (scheduler: TimedStack#pop).
gem "connection_pool", "~> 2.4"
gem "sidekiq", "~> 7.3"

gem "rack-attack"
gem "rack-cors"
gem "csv"

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "bootsnap", require: false

gem "kamal", require: false
gem "thruster", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  # Loads .env when Rails and Sidekiq start (Sidekiq is a separate process from your shell).
  gem "dotenv-rails"
end
